export const Herramientas = [
  {
    id_pestana: 16,
    c_nomb_pestana: "Administracion",
    c_div_pestana: "administracion",
    c_boton_pestana: "AdministracionIcon",
    c_accion_pestana: "openProcess",
    grupos: [
      {
        id_grupo: 49,
        c_nomb_grupo: "Grupo Prueba",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 101,
            c_nomb_herramienta: "Prueba",
            c_icono_herramienta: "fa fa-sticky-note",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-layerx-ex",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 13,
    c_nomb_pestana: "Auditoria",
    c_div_pestana: "auditoria",
    c_boton_pestana: "AuditoriaIcon",
    c_accion_pestana: "openProcess",
    grupos: [
      {
        id_grupo: 39,
        c_nomb_grupo: "Usuario",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 71,
            c_nomb_herramienta: "Reporte de usuario",
            c_icono_herramienta: "fa fa-user-secret",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-auditoria-reporte-usuario",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 3,
    c_nomb_pestana: "Busqueda",
    c_div_pestana: "busqueda",
    c_boton_pestana: "BusquedaIcon",
    c_accion_pestana: "openMap",
    grupos: [
      {
        id_grupo: 8,
        c_nomb_grupo: "Busqueda",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 30,
            c_nomb_herramienta: "Por Sector Mzna y Lote",
            c_icono_herramienta: "fa fa-globe",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-search-spacial-sml",
          },
          {
            id_herramienta: 55,
            c_nomb_herramienta: "por coordenadas",
            c_icono_herramienta: "fa fa-search",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-buscadorCoord",
          },
          {
            id_herramienta: 56,
            c_nomb_herramienta: "por vias & cuadras",
            c_icono_herramienta: "fa fa-search",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-buscadorViasCuadras",
          },
          {
            id_herramienta: 99,
            c_nomb_herramienta: "Por Via y  Cuadra",
            c_icono_herramienta: "fa fa-road",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-buscadorViasCuadras",
          },
          {
            id_herramienta: 100,
            c_nomb_herramienta: "Por Coordenada",
            c_icono_herramienta: "fa fa-map-marker",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-buscadorCoord",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 2,
    c_nomb_pestana: "Capas",
    c_div_pestana: "capas",
    c_boton_pestana: "CapasIcon",
    c_accion_pestana: "openMap",
    grupos: [
      {
        id_grupo: 7,
        c_nomb_grupo: "Agregar Capas",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 19,
            c_nomb_herramienta: "WMS",
            c_icono_herramienta: "fa fa-bars",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-wms",
          },
          {
            id_herramienta: 20,
            c_nomb_herramienta: "KML",
            c_icono_herramienta: "fa fa-bars",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-kml",
          },
        ],
      },
      {
        id_grupo: 6,
        c_nomb_grupo: "Capas",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 17,
            c_nomb_herramienta: "Capas",
            c_icono_herramienta: "fimg fimg-layer",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-externalLayer",
          },
          {
            id_herramienta: 18,
            c_nomb_herramienta: "Leyenda",
            c_icono_herramienta: "fa fa-book",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-legend",
          },
        ],
      },
      {
        id_grupo: 54,
        c_nomb_grupo: "Filtrar",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 119,
            c_nomb_herramienta: "Encuesta",
            c_icono_herramienta: "fa fa-filter",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-FiltroEncuesta",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 5,
    c_nomb_pestana: "Catastro",
    c_div_pestana: "fichas",
    c_boton_pestana: "CatastroIcon",
    c_accion_pestana: "openProcess",
    grupos: [
      {
        id_grupo: 14,
        c_nomb_grupo: "Consultas",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 36,
            c_nomb_herramienta: "Consulta Fichas",
            c_icono_herramienta: "fa fa-search",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-consulta-ficha",
          },
          {
            id_herramienta: 37,
            c_nomb_herramienta: "Validación Grafica Alfanumérica",
            c_icono_herramienta: "fa fa-check",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-valalfnum",
          },
          {
            id_herramienta: 54,
            c_nomb_herramienta: "Reporte CUC",
            c_icono_herramienta: "fa fa-search",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-reporte-cuc",
          },
        ],
      },
      {
        id_grupo: 11,
        c_nomb_grupo: "Rural",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 27,
            c_nomb_herramienta: "UU. CC. Rurales",
            c_icono_herramienta: "fimg fimg-layer",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-unicatru",
          },
        ],
      },
      {
        id_grupo: 10,
        c_nomb_grupo: "Urbano",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 26,
            c_nomb_herramienta: "UU. CC. Urbanas",
            c_icono_herramienta: "fimg fimg-layer",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-unicat",
            url: "/dashboard/unicat",
          },
          {
            id_herramienta: 38,
            c_nomb_herramienta: "Reportes  Espaciales",
            c_icono_herramienta: "fa fa-globe",
            c_boton_herramienta: null,
            c_modal_herramienta: "div-reporte-espacial",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 19,
    c_nomb_pestana: "Estadistica II",
    c_div_pestana: "estadisticaII",
    c_boton_pestana: "EstadisticaIcon",
    c_accion_pestana: "openProcess",
    grupos: [
      {
        id_grupo: 52,
        c_nomb_grupo: "Grafica",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 116,
            c_nomb_herramienta: "Ver grafica",
            c_icono_herramienta: "fa fa-bar-chart",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-estadistica",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 15,
    c_nomb_pestana: "Fiscalizacion",
    c_div_pestana: "fiscalizacion",
    c_boton_pestana: "FiscalizacionIcon",
    c_accion_pestana: "openProcess",
    grupos: [
      {
        id_grupo: 42,
        c_nomb_grupo: "Identificacion",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 75,
            c_nomb_herramienta: "Subvaluadores",
            c_icono_herramienta: "fa fa-plus",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-subvaluadores",
          },
          {
            id_herramienta: 88,
            c_nomb_herramienta: "Omisos",
            c_icono_herramienta: "fa fa-plus",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-omisos",
          },
        ],
      },
      {
        id_grupo: 44,
        c_nomb_grupo: "Informe",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 85,
            c_nomb_herramienta: "Informe tecnico",
            c_icono_herramienta: "fa fa-newspaper-o",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-informe",
          },
        ],
      },
      {
        id_grupo: 43,
        c_nomb_grupo: "Requerimiento",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 83,
            c_nomb_herramienta: "Formato",
            c_icono_herramienta: "fa fa-file-word-o",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-formatoreque",
          },
          {
            id_herramienta: 89,
            c_nomb_herramienta: "Reprogramacion",
            c_icono_herramienta: "fa fa-file-word-o",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-reprograma",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 6,
    c_nomb_pestana: "Maestros",
    c_div_pestana: "maestros",
    c_boton_pestana: "MaestroIcon",
    c_accion_pestana: "openProcess",
    grupos: [
      {
        id_grupo: 12,
        c_nomb_grupo: "Mantenimiento de Maestros",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 28,
            c_nomb_herramienta: "Maestros  Urbanos",
            c_icono_herramienta: "fa fa-briefcase",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-maesurb",
          },
          {
            id_herramienta: 29,
            c_nomb_herramienta: "Maestros  Rurales",
            c_icono_herramienta: "fa fa-briefcase",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-maesru",
          },
        ],
      },
      {
        id_grupo: 45,
        c_nomb_grupo: "Mobile",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 90,
            c_nomb_herramienta: "Gestión de Encuesta",
            c_icono_herramienta: "fa fa-mobile",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-maestros-mobile",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 4,
    c_nomb_pestana: "Seguridad",
    c_div_pestana: "seguridad",
    c_boton_pestana: "SeguridadIcon",
    c_accion_pestana: "openProcess",
    grupos: [
      {
        id_grupo: 36,
        c_nomb_grupo: "Maestros",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 59,
            c_nomb_herramienta: "Grupos y Supergrupos",
            c_icono_herramienta: "fa fa-object-group",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-mgys",
          },
        ],
      },
      {
        id_grupo: 9,
        c_nomb_grupo: "Seguridad",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 22,
            c_nomb_herramienta: "Roles",
            c_icono_herramienta: "fa fa-briefcase",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-roles",
          },
          {
            id_herramienta: 23,
            c_nomb_herramienta: "Usuarios",
            c_icono_herramienta: "fa fa-user",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-usuarios",
          },
          {
            id_herramienta: 24,
            c_nomb_herramienta: "Menu por Rol",
            c_icono_herramienta: "fa fa-server",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-menu-rol",
          },
          {
            id_herramienta: 25,
            c_nomb_herramienta: "Capas por Rol",
            c_icono_herramienta: "fimg fimg-layer",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-configLayer",
          },
          {
            id_herramienta: 40,
            c_nomb_herramienta: "Gestión de capas",
            c_icono_herramienta: "fimg fimg-layer",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-gestCapas",
          },
          {
            id_herramienta: 41,
            c_nomb_herramienta: "Gestión de Herramientas",
            c_icono_herramienta: "fa fa-cogs",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-gestHerra",
          },
          {
            id_herramienta: 57,
            c_nomb_herramienta: "Gestión de Herramientas Super Admin",
            c_icono_herramienta: "fa fa-cogs",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-gestHerraSuperAdmin",
          },
          {
            id_herramienta: 58,
            c_nomb_herramienta: "Menú por Cliente",
            c_icono_herramienta: "fa fa-server",
            c_boton_herramienta: null,
            c_modal_herramienta: "nav-menu-rol-sa",
          },
        ],
      },
    ],
  },
  {
    id_pestana: 7,
    c_nomb_pestana: "Temáticos",
    c_div_pestana: "tematicos",
    c_boton_pestana: "TematicoIcon",
    c_accion_pestana: "openMap",
    grupos: [
      {
        id_grupo: 48,
        c_nomb_grupo: "Comercializacion",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 96,
            c_nomb_herramienta: "Giros Comerciales",
            c_icono_herramienta: "fa fa-shopping-cart",
            c_boton_herramienta: null,
            c_modal_herramienta: "Giros Comerciales",
          },
          {
            id_herramienta: 97,
            c_nomb_herramienta: "Licencia de Funcionamiento",
            c_icono_herramienta: "fa fa-id-card",
            c_boton_herramienta: null,
            c_modal_herramienta: "Licencia de Funcionamiento",
          },
          {
            id_herramienta: 98,
            c_nomb_herramienta: "Licencia de Anuncios",
            c_icono_herramienta: "fa fa-id-card-o",
            c_boton_herramienta: null,
            c_modal_herramienta: "Licencia de Anuncios",
          },
        ],
      },
      {
        id_grupo: 46,
        c_nomb_grupo: "Construccion",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 91,
            c_nomb_herramienta: "Material Predominante",
            c_icono_herramienta: "fa fa-home",
            c_boton_herramienta: null,
            c_modal_herramienta: "Material Predominante",
          },
          {
            id_herramienta: 92,
            c_nomb_herramienta: "Estado de Construccion",
            c_icono_herramienta: "fa fa-building-o",
            c_boton_herramienta: null,
            c_modal_herramienta: "Estado de Construccion",
          },
          {
            id_herramienta: 93,
            c_nomb_herramienta: "Estado de Conservacion",
            c_icono_herramienta: "fa fa-building",
            c_boton_herramienta: null,
            c_modal_herramienta: "Estado de Conservacion",
          },
        ],
      },
      {
        id_grupo: 47,
        c_nomb_grupo: "Otros",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 94,
            c_nomb_herramienta: "Habitantes por Manzana",
            c_icono_herramienta: "fa fa-users",
            c_boton_herramienta: null,
            c_modal_herramienta: "Habitantes por Manzana",
          },
          {
            id_herramienta: 95,
            c_nomb_herramienta: "Tipo de Via",
            c_icono_herramienta: "fa fa-road",
            c_boton_herramienta: null,
            c_modal_herramienta: "Tipo de Via",
          },
        ],
      },
      {
        id_grupo: 13,
        c_nomb_grupo: "Servicios",
        b_grupo: true,
        herramientas: [
          {
            id_herramienta: 31,
            c_nomb_herramienta: "Cobertura de Agua",
            c_icono_herramienta: "fa fa-tint",
            c_boton_herramienta: null,
            c_modal_herramienta: "cobertura agua",
          },
          {
            id_herramienta: 32,
            c_nomb_herramienta: "Cobertura de Desagüe",
            c_icono_herramienta: "fa fa-beer",
            c_boton_herramienta: null,
            c_modal_herramienta: "cobertura desague",
          },
          {
            id_herramienta: 33,
            c_nomb_herramienta: "Cobertura de Gas",
            c_icono_herramienta: "fa fa-fire",
            c_boton_herramienta: null,
            c_modal_herramienta: "cobertura gas",
          },
          {
            id_herramienta: 34,
            c_nomb_herramienta: "Cobertura de Luz",
            c_icono_herramienta: "fa fa-bolt",
            c_boton_herramienta: null,
            c_modal_herramienta: "cobertura luz",
          },
          {
            id_herramienta: 35,
            c_nomb_herramienta: "Cobertura de Teléfono",
            c_icono_herramienta: "fa fa-phone",
            c_boton_herramienta: null,
            c_modal_herramienta: "cobertura telefono",
          },
        ],
      },
    ],
  },
];
